In [4]:
# Name: Alejandro Blancas
# Date: 17-2-2021

In [28]:
# Problem 1
# Use NumPy RNG to create array of twelve random grades
# range 60 through 100, then reshape into 3-by-4 array
# Find average all grade, column, & row
import numpy as np
import random

grades = np.random.randint(60,101,12).reshape(3,4)
grades

array([[82, 72, 76, 74],
       [79, 67, 83, 80],
       [64, 91, 84, 77]])

In [29]:
# Answer 1:
print(f'Average of All Grades = {grades.mean():.2f}')

Average of All Grades = 77.42


In [30]:
# Answer 2:
print(f'Average of the grades in each column = {grades.mean(axis=0)}')

Average of the grades in each column = [75.         76.66666667 81.         77.        ]


In [32]:
# Answer 3:
print(f'Average of the grades in each row = {grades.mean(axis=1)}')

Average of the grades in each row = [76.   77.25 79.  ]


In [40]:
# Problem 2
# Given the following array
# Write statements to perform the following tasks:
# 1. Select second row 2. Select first & third row
# 3. Select middle three columns
numbers = np.arange(1,16).reshape(3,5)
numbers

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [41]:
# Answer 1:
numbers[1]

array([ 6,  7,  8,  9, 10])

In [42]:
# Answer 2:
numbers[[0,2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [43]:
# Answer 3:
numbers[:, 1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [49]:
# Problem 3
# Given a 2-by-3 array
numbers2 = np.arange(1,7).reshape(2,3)
numbers2

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
# Use hstack and vstack to produce the following array
# Answer 1:
numbers2 = np.arange(1,7).reshape(2,3)
numbers2 = np.hstack((numbers2,numbers2))
numbers2 = np.vstack((numbers2,numbers2))
numbers2

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])