In [1]:
# Problem 1
# Create 2 by 5 array containing even & odd int (2-10) 
# using list comprehension

In [3]:
# answer
import numpy as np
numbers = np.array([[x for x in range(2,11,2)],[x for x in range(1,10,2)]])
numbers

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [5]:
# display numbers of dimensions and shape type
# and size of array

In [6]:
numbers.ndim

2

In [7]:
numbers.shape

(2, 5)

In [8]:
numbers.dtype

dtype('int32')

In [9]:
numbers.size

10

In [10]:
# use NumPy to create array (20 even) (2-40) then reshape
# 4-by-5 array

In [11]:
np.arange(2,41,2).reshape(4,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [12]:
# Problem 2
# Use NumPy's RNG to create array of five random ints (temp 60-100)

In [13]:
import pandas as pd
temps = np.random.randint(60, 101, 6)
temps

array([66, 84, 89, 70, 67, 90])

In [14]:
# Create array into Series named temperatures and display it

In [15]:
temperatures = pd.Series(temps)
temperatures

0    66
1    84
2    89
3    70
4    67
5    90
dtype: int32

In [16]:
# Determine the lowest, highest, and avearge temps

In [17]:
print(f'Lowest = {temperatures.min():.2f}')
print(f'Highest = {temperatures.max():.2f}')
print(f'Average = {temperatures.mean():.2f}')

Lowest = 66.00
Highest = 90.00
Average = 77.67


In [18]:
# Produce the descriptive statistics for Series

In [20]:
temperatures.describe()

count     6.000000
mean     77.666667
std      11.219031
min      66.000000
25%      67.750000
50%      77.000000
75%      87.750000
max      90.000000
dtype: float64

In [22]:
# Covert dict into DF with low & high as indices then display

In [37]:
Temps = {'Mon': [68, 89], 'Tue': [71, 93], 'Wed': [66, 82], 'Thu': [75, 97], 'Fri': [62, 79]}
Temps

{'Mon': [68, 89],
 'Tue': [71, 93],
 'Wed': [66, 82],
 'Thu': [75, 97],
 'Fri': [62, 79]}

In [40]:
temperatures = pd.DataFrame(Temps, index = ['Low', 'High'])
temperatures

Mon  Tue  Wed  Thu  Fri
Low    68   71   66   75   62
High   89   93   82   97   79

In [41]:
# select only the columns for Mon through Wed

In [42]:
temperatures.loc[:, 'Mon': 'Wed']

Mon  Tue  Wed
Low    68   71   66
High   89   93   82

In [43]:
# Select Mon - Wed - Fri columns

In [45]:
temperatures.loc[:, ['Mon','Wed','Fri']]

Mon  Wed  Fri
Low    68   66   62
High   89   82   79

In [46]:
# Use row index 'Low' to select only the low temperatures for each day

In [47]:
temperatures.loc['Low']

Mon    68
Tue    71
Wed    66
Thu    75
Fri    62
Name: Low, dtype: int64

In [48]:
# Select high temps for Tue - Thu - Fri

In [49]:
temperatures.loc['High',['Tue', 'Thu','Fri']]

Tue    93
Thu    97
Fri    79
Name: High, dtype: int64