In [1]:
# 7.2 Creating arrays from Existing Data
# Use array function which recieves as an argument an array
# or other collection of elements and returns a new array
# contating the argument's elements

import numpy as np

numbers = np.array([2,5,7,11]) # pass a list
numbers
#print(numbers)

array([ 2,  5,  7, 11])

In [2]:
type(numbers)

numpy.ndarray

In [3]:
# Multidimensional Arguments
numbers2 = np.array([[1,2,3],[4,5,6]])
numbers2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# Create a one dimensional array from a list comprehension
# that produces the even integer from 2 through 20

np.array([x for x in range(2,21,2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
print(np.array([x for x in range(2,21,2)]))

[ 2  4  6  8 10 12 14 16 18 20]


In [6]:
# 7.3 array attributes 
# attributes enable you to discover info about its structure and contents
# NumPy does not display trailing 0s to the right of the decimal point in floating-point values.

In [7]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [9]:
integers = np.array([[1,2,3], [4,5,6]])
integers.dtype

dtype('int32')

In [10]:
# Determining an array's Element Type
floats.dtype

dtype('float64')

In [11]:
# Determining an array's Dimensions
# ndim contains an array's numbers of dimensions
# shape contains a tuple specifiying an array's dimensions

In [12]:
floats.ndim

1

In [13]:
integers.ndim

2

In [14]:
# The attribute shape contains a tuple specifying an array's dimensions
integers.shape # 2 rows, 3 columns = 6 elements

(2, 3)

In [15]:
floats.shape # one dimensional

(5,)

In [17]:
# Determining an array's Number of Elements and Elements Size
# View an array's total number of elements with atrribute size
integers.size

6

In [18]:
floats.size

5

In [19]:
# The number of bytes required to store each elements with itemsize
integers.itemsize # 8 if C compiler uses 64-bit ints

4

In [20]:
floats.itemsize

8

In [22]:
# Iterating through a Multidimensional array's Elements
# A multidimensional array as if it were one-dimensional by using flat
for row in integers:
    for column in row:
        print(column, end = '   ')
    print()

1   2   3   
4   5   6   


In [23]:
for row in integers:
    print(row, end = '   ')

[1 2 3]   [4 5 6]   

In [24]:
for row in integers:
    print(row)

[1 2 3]
[4 5 6]


In [25]:
for i in integers.flat:
    print(i, end = '   ')

1   2   3   4   5   6   

In [26]:
# 7.4 Filling Array with Specific Values
# NumPy provides functions zeros, ones, and full for creating
# arrays containing 0s,1s, or specified value.

In [27]:
np.zeros(5) # default id float64 values

array([0., 0., 0., 0., 0.])

In [28]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [29]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.ones((2,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [31]:
np.full((3,5), 13.0)

array([[13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13.],
       [13., 13., 13., 13., 13.]])

In [32]:
# 7.5 Creating arrays from Ranges
# arange function
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [34]:
np.arange(9.3,1,-2)

array([9.3, 7.3, 5.3, 3.3, 1.3])

In [35]:
# linspace function
# Produce evenly spaced floating-point range with NumPy's linespace function
# First two arguments specify the starting and ending values in the range,
# and the ending value is included in the array.
# The optional keyword argument num specifies the number of evenly spaced values to produce
# - this argument's default values is 50

np.linspace(0.0, 1.0, num = 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [36]:
np.linspace(0, 100, num = 5)

array([  0.,  25.,  50.,  75., 100.])

In [37]:
np.linspace(0, 100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [39]:
# Respace to transform the one-dimensional array into a multidimensional array
ss =np.arange(1,21)
ss

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
ss.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [41]:
ss

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [42]:
# In one line.
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [43]:
# Display first three and last three to display big array
np.arange(1,100001).reshape(4,25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [44]:
np.arange(1,100001).reshape(100,1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])