In [2]:
import numpy as np
# 7.7 Array Operators
# Arithmetic Operations with arrays and Individual Numeric Values
numbers = np.arange(1,6)
print(numbers)
print(numbers * 2)
print(numbers) # numbers is unchanged by the arithmetic operators

[1 2 3 4 5]
[ 2  4  6  8 10]
[1 2 3 4 5]


In [3]:
# Augmented assignments modify every element in the left operand
numbers = numbers + 10
numbers

array([11, 12, 13, 14, 15])

In [4]:
# Arithmetic Operations between arrays
numbers2 = np.linspace(1.1, 5.5, 5)
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [5]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [6]:
# Comparing Arrays
# Comparsions are peformed element-wise
# Such comparsions produce array of Boolean values (True or False)
numbers

array([11, 12, 13, 14, 15])

In [7]:
numbers >= 13

array([False, False,  True,  True,  True])

In [8]:
numbers2 <numbers

array([ True,  True,  True,  True,  True])

In [9]:
numbers == numbers2

array([False, False, False, False, False])

In [10]:
# 7.8 NumPy Calculation Methods (sum, min, max, mean, std, var)
# Consider an array representing four students' grades on three exams
grades = np.array([[87,96,70], [100,87,90], [94,77,90], [100,81,82]])
grades


array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [13]:
print(grades.sum())
print(grades.min())
print(grades.max())
print(f'{grades.mean():.2f}')
print(grades.std())
print(grades.var())

1054
70
100
87.83
8.792357792739987
77.30555555555556


In [14]:
# Calculations by Row or Column based an array's axes
# axis = 0 peforms the calculation on all the row values with each column
# To calculate average of each exam
grades.mean(axis= 0)

array([95.25, 85.25, 83.  ])

In [15]:
# axis = 1 performs the calculation on all the column values with in each individual row
# To calculate each student's average grade for all exams
grades.mean(axis = 1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [16]:
# 7.9 Universal Functions (refer to PG.254)
# Sqrt universal function
numbers = np.array([1,4,9,16,25,36])
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [17]:
numbers

array([ 1,  4,  9, 16, 25, 36])

In [18]:
numbers2 = np.arange(1,7) * 10
numbers2

array([10, 20, 30, 40, 50, 60])

In [19]:
# add universal function with same shape
np.add(numbers, numbers2)

array([11, 24, 39, 56, 75, 96])

In [22]:
# multiply universal function
np.multiply(numbers2, 5) # same as number2 *5

array([ 50, 100, 150, 200, 250, 300])

In [23]:
# Reshape numbers2 into 2 by 3 array
numbers3 = numbers2.reshape(2,3)
numbers3

array([[10, 20, 30],
       [40, 50, 60]])

In [24]:
numbers4 = np.array([2,4,6])
numbers4

array([2, 4, 6])

In [26]:
np.multiply(numbers3, numbers4)

# numbers4 has the same length as each row of numbers3, so NumPy can apply
# the multiply operation by treating numbers4 as if [[2,4,6], [2,4,6]]
# otherwise a valueerror occurs

array([[ 20,  80, 180],
       [ 80, 200, 360]])

In [27]:
np.add(numbers3, numbers4)

array([[12, 24, 36],
       [42, 54, 66]])

In [28]:
# 7.10 Indexing and Slicing
# Indexing with Two-Dimensional arrays
# To select an element in a two dimensional array
grades = np.array([[87,96,70], [100,87,90], [94,77,90], [100,81,82]])
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [29]:
grades[0,1] # row 0 column 1

96

In [30]:
# Selecting a subset of Two-Dimensional array's rows
# To select a single row, specify only one index in square brackets
grades[0]

array([87, 96, 70])

In [31]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [32]:
grades[1:3]

array([[100,  87,  90],
       [ 94,  77,  90]])

In [33]:
# Selecting a subset of Two-Dimensional array's columns
# Specifying the rows and columns to select
# To select only the elements in the first column
grades[:, 0]

array([ 87, 100,  94, 100])

In [34]:
# To select consecutive columns using slice - column1 to column2 for all rows
grades[:, 1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [35]:
# To select specific columns using a list of column indices - column 0 and column2 for all rows
grades[:, [0,2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

In [36]:
# 7.13 Reshaping and Transposing
# Reshape does not modify the original array
grades = np.array([[87, 96, 70],[100, 87, 90]])
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [37]:
grades.reshape(1,6)

array([[ 87,  96,  70, 100,  87,  90]])

In [38]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [39]:
# Resize modifies the original array's shape
grades.resize(1,6)
grades

array([[ 87,  96,  70, 100,  87,  90]])

In [40]:
# Transposing Rows and Columns
# HStack
# VStack
# Horizontal and Vertical Stacking
# You can combine arrays by adding more columns or more rows
grades = np.array([[87, 96, 70], [100, 87, 90]])
grades2 = np.array([[94, 77, 90], [100, 81, 82]])
# Grades2 represent three additional exam grades for the two students
np.hstack((grades, grades2))

array([[ 87,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

In [41]:
np.vstack((grades, grades2)) # Two more students' grades on three exams

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])